name: Android CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        working-directory: TicketApp
        run: chmod +x gradlew

      - name: Build + Unit Tests + Coverage
        working-directory: TicketApp
        run: ./gradlew --no-daemon clean testDebugUnitTest jacocoTestReport assembleDebug

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TicketApp/app/build/reports/tests/

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: TicketApp/app/build/reports/jacoco/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: TicketApp/app/build/outputs/apk/debug/app-debug.apk